source "http://rubygems.org"

ruby "2.2.1"
gem "rails", "4.2.0"

gem "awesome_print"
gem "cancancan"
gem "clockwork"
gem "coffee-rails"
gem "devise"
gem "devise-async"
gem "devise_invitable"
gem "ember-rails"
gem "ember-source"
gem "gibberish"
gem "highline"
gem "jbuilder"
gem "jquery-rails"
gem "local_time"
gem "money-rails", github: "RubyMoney/money-rails"
gem "omniauth"
gem "paranoia"
gem "pg"
gem "puma"
gem "rack-cors", require: "rack/cors"
gem "rest-client"
gem "roadie"
gem "roadie-rails"
gem "sass-rails"
gem "sidekiq"
gem "sidekiq_mailer"
gem "sinatra"
gem "stripe"
gem "uglifier"

group :development, :test do
  gem "byebug"
  gem "dotenv-rails"
  gem "factory_girl_rails"
  gem "foreman"
  gem "letter_opener_web"
  gem "quiet_assets"
  gem "rspec-rails"
  gem "spring"
  # gem "web-console", "~> 2.0.0.beta4"
end

group :test do
  gem "capybara"
  gem "database_cleaner"
  gem "faker"
  gem "guard"
  gem "guard-rspec"
  gem "rb-fsevent"
  gem "terminal-notifier-guard"
  gem "webmock"
end
