# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f435136969824af9606f71924bf9647166e93fb75eb259a7e5e9e9e13fabe2c3ea9fac3c2f3bdef7fed9bf92cc2bfad36152be570192ca9d71dc5da75bea4e31

test:
  secret_key_base: 9c0eb556f04777957d34667f2339a94b835d35c585a92278651e684a22c6a325aeca95f68712747c661912f4aedb96e147bb6caf0a206aa135b186c56d463666

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
